<h1>Registration</h1>
<form name="fomr1" method="post">
<table style="width:100%">
    <tr>
        <td>Enter Email</td>
        <td><input type="text" name="email"></td>
    </tr>
    <tr>
        <td>Enter Phone No</td>
        <td><input type="text" name="phno"></td>
    </tr>
    <tr>
        <td>Enter Address</td>
        <td><input type="textarea" name="address"></td>
    </tr>
    <tr>
        <td>Type of Proof</td>
        <td><select id="proof">
                <option value="Voterid">Voterid</option>
                <option value="Passport">Passport</option>
            </select></td>
    </tr>
    <tr>
        <td>Upload Document</td>
        <td><input type="file" name="addressproof"></td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td><input type="submit" name="save"></td>
    </tr>
</table>
</form>