<div class="jumbotron">
    <h1></h1>
    <p>
    </p>
    <p></p>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Login</h3>
            </div>
            <form id="form1" name="form1">
            <table>
                <tr>
                    <td>User Name</td>
                    <td><input type="text" name="username"></td>
                </tr>
                <tr>
                    <td>Password</td>
                    <td><input type="password" name="password"></td>
                </tr>
                <tr>
                    <td><p><a class="btn btn-success pull-right" href="#" target="_blank">Sign Up</a></p></td>
                    <td><input class="btn btn-success pull-right" type="submit" name="Login" value="Login"></td>
                </tr>
            </table>
            </form>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"></h3>
            </div>
            <div class="panel-body">
                <p></p>
<!--                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"></a></p>-->
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"></h3>
            </div>
            <div class="panel-body">
                <p></p>
<!--                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"></a></p>-->
            </div>
        </div>
    </div>
</div>
